version: '3.3'

# For development
services:

    # Database
    mysql_colors_multiplica_test:
        image: mysql:5.7
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: 'color-db'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        volumes: 
            - ./mysql_data:/var/lib/mysql
        restart: "no"

    # Database Admin
    phpmyadmin_database_multiplica_colors:
        depends_on:
            - mysql_colors_multiplica_test
        image: phpmyadmin/phpmyadmin
        restart: "no"
        ports:
            - '8082:80'
        environment:
            PMA_HOST: 'mysql_colors_multiplica_test'
            MYSQL_ROOT_PASSWORD: 'password'            